apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
spec:
  llm:
    providers:
    - credentialsSecretRef:
        name: bam-api-keys
      type: bam
      models:
      - name: ibm/granite-13b-chat-v2
      name: bam
      url: https://bam-api.res.ibm.com
  ols:
    conversationCache:
      redis:
        maxMemory: 2000mb
        maxMemoryPolicy: allkeys-lru
      type: redis
    defaultModel: ibm/granite-13b-chat-v2
    defaultProvider: bam
    logLevel: INFO
    useUserProvidedTLSCerts: true
    deployment:
      replicas: 1
      console:
        caCertificate: |
          -----BEGIN CERTIFICATE-----
          your-certificate content, syntax sensitive
          -----END CERTIFICATE-----
